package com.stockexchange.concurrency;

import java.util.concurrent.Callable;
import java.util.concurrent.Future;

public class CallableDemo {

    public static void main(String[] args) {

        TradingExecutor executor = new TradingExecutor(3);

        Callable<String> task = () -> {

            String threadName =
                    Thread.currentThread().getName();

            return "Order generated by " + threadName;
        };

        Future<String> future = executor.submit(task);

        try {

            String result = future.get();

            System.out.println(result);

        } catch (Exception e) {

            e.printStackTrace();

        } finally {

            executor.shutdown();
            executor.awaitCompletion();
        }
    }
}